### ISSUE TITLE
Bug extracting previews

### ISSUE THREAD

**Issue by FrodeMMeling** [beryllium/rawr#1]
I think there is a bug in this library.
https://github.com/beryllium/rawr/blob/master/Rawr.php#L39

I am extracting 1 preview and not 3. So this seems to work only for 3:
Suggested fix:
`$outputFile = str_ireplace('.cr2', '-preview' . $index . '.jpg', $outputFile);`

Also : 
https://github.com/beryllium/rawr/blob/master/Rawr.php#L55
Has a namespace issue.
Suggested fix:
`throw new \RuntimeException('Extraction failed!');`

Same issue probably goes for L36

**Comment by beryllium** [comment]
Thanks for the bug report! I've released v1.1.0 of Rawr, which should fix these issues. It adds an extra check for the previews list in order to get the correct file extension, hence the jump from 1.0.1 to 1.1.0 - it could introduce slightly slower performance.

Please let me know if the fix is successful (or if there are still issues to be resolved). Thanks again!
